name: "CS50 CI"
description: "Continuous Integration workflow for testing CS50 problem sets"
author: "Leon Kleinschmidt"

inputs:
  app-id:
    description: "GitHub App ID used to authenticate"
    required: true
  install-id:
    description: "GitHub App Installation ID"
    required: true
  private-key:
    description: "GitHub App private key (B64)"
    required: true
  problems-repository: 
    description: "Full name of the repository containing the problems tests (e.g. cs50/problems)"
    required: true
  problems-branch: 
    description: "Branch name of the problems repository to use (e.g. main)"
    required: true
  solutions-repository:
    description: "Full name of the repository containing the solution (e.g. cs50/solutions)"
    required: true
  solutions-branch: 
    description: "Branch name of the solutions repository to use (e.g. main)"
    required: true

runs:
  using: docker
  image: docker://ghcr.io/leokle/cs50-ci-action:latest
  env:
    APP_ID: ${{ inputs.app-id }}
    INSTALL_ID: ${{ inputs.install-id }}
    PRIVATE_KEY_B64: ${{ inputs.private-key }}
    PROBLEMS_REPO: ${{ inputs.problems-repository }}
    PROBLEMS_BRANCH: ${{ inputs.problems-branch }}
    SOLUTIONS_REPO: ${{ inputs.solutions-repository }}
    SOLUTIONS_BRANCH: ${{ inputs.solutions-branch }}

branding:
  icon: "check-circle"
  color: "blue"
