name: "CS50 CI"
description: "Continuous Integration workflow for testing CS50 problem sets"
author: "Leon Kleinschmidt"

inputs:
  app-id:
    description: "GitHub App ID used to authenticate"
    required: true
  install-id:
    description: "GitHub App Installation ID"
    required: true
  private-key:
    description: "GitHub App private key (B64)"
    required: true
  problems-repository: 
    description: "Full name of the repository containing the problems tests (e.g. cs50/problems)"
    required: true
  solutions-repository:
    description: "Full name of the repository containing the solution (e.g. cs50/solutions)"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    APP_ID: ${{ inputs.app-id }}
    INSTALL_ID: ${{ inputs.install-id }}
    PRIVATE_KEY: ${{ inputs.private-key }}
    PROBLEMS_REPO: ${{ inputs.problems-repository }}
    SOLUTIONS_REPO: ${{ inputs.solutions-repository }}

branding:
  icon: "check-circle"
  color: "blue"
